# Generated by Django 4.2.13 on 2024-06-26 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'todo'), (2, 'InProgress'), (3, 'Done')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
